server:
  port: 8089

#是否开启 swagger-ui
swagger:
  enabled: true

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 3000MB
      max-request-size: 3000MB

# 文件存储路径
file:
  mac:
    path: ~/file/
    rootPath: ~/file/audio_root/ #压缩包解压缩文件夹
  linux:
    path: /home/aias/file/
    rootPath: /home/aias/file/audio_root/ #压缩包解压缩文件夹
  windows:
    path: file:/D:/aias/file/
    rootPath: file:/D:/aias/file/audio_root/ #压缩包解压缩文件夹
  # 文件大小 /M
  maxSize: 3000

# Voice 
audio:
  # 特征提取模型
  feature: https://aias-home.oss-cn-beijing.aliyuncs.com/models/speech_models/voiceprint.zip
  #  path: /Users/calvin/Documents/audio_root/ #文件存放文件夹
  baseUrl: http://127.0.0.1:8089/files/
  
# Vector Engine - Milvus
search:
  host: 127.0.0.1
  port: 19530

  # https://milvus.io/cn/docs/v2.0.0/build_index.md
  # https://milvus.io/cn/docs/v2.0.0/metric.md#floating
  # For floating point vectors:
  #  IVF_FLAT
  #  IVF_SQ8
  #  IVF_PQ
  #  HNSW
  #  ANNOY
  #  RHNSW_FLAT
  #  RHNSW_PQ
  #  RHNSW_SQ
  # For binary vectors:
  #  BIN_IVF_FLAT
  indexType: IVF_FLAT
  metricType: L2

  nprobe: 256
  nlist: 16384
  dimension: 512 # dimension of each vector
  collectionName: voiceprint #collection name
  partitionName: p1