
spring:
  profiles:
    active: win
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8

# Swagger-ui
swagger:
  enabled: true

# File path
file:
  mac:
    path: file/
  linux:
    path: file/
  windows:
    path: C:\\iocr\\file\\
  # File max size - MB
  maxSize: 100


# Verify image transformation result
image:
  debug: true
  # 设置图片摆正对齐透视变换次数的上限
  maxNum: 4
  # 4个锚点框对应的4边形的4个顶点，与待识别图片检测框对应的4个顶点距离
  disThreshold: 3

# distance calculation type: L2, IoU
distance:
  type: IoU


